### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1015: character maps to <undefined>

### ISSUE THREAD

**Issue by nicolasvillatte** [Ge0rg3/sans-index-creator#3]
Upon execution I receive the following error message:
Traceback (most recent call last):
  File "C:\Users\Blah\Downloads\sans-index-creator-master\sans_indexer.py", line 69, in <module>
    data = f.read()
  File "C:\Python\Python3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1015: character maps to <undefined>

**Comment by nicolasvillatte** [comment]
fixed by adding ', encoding='utf8'' to the open of the input page
