### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u2010' in position 4: character maps to <undefined>

### ISSUE THREAD

**Issue by nicolasvillatte** [Ge0rg3/sans-index-creator#4]
Error received upon execution
Traceback (most recent call last):
  File "C:\Users\Blah\Downloads\sans-index-creator-master\sans_indexer.py", line 120, in <module>
    f.write(result + "\n")
  File "C:\Python\Python3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2010' in position 4: character maps to <undefined>

Same utf-8 issue when opening file for write.

**Comment by nicolasvillatte** [comment]
solved by specifying , encoding='utf8' for the open before the write in line 120
